"use client";
import { useState } from "react";

const targets=["2K 光追游戏","4K 视频剪辑","本地 AI 绘图"];
const parts=[["CPU","Ryzen 5 7600X","6 核 · AM5"],["GPU","RTX 4070 SUPER","12GB · 330mm"],["主板","B650M MORTAR","AM5 · DDR5"],["内存","DDR5 6000 32GB","CL30 · 双通道"],["散热","PA120 SE","155mm · 风冷"],["电源","750W ATX 3.0","峰值余量 34%"]];
export default function Home(){const [target,setTarget]=useState(0);const [quiet,setQuiet]=useState(false);const [tuned,setTuned]=useState(false);const [tip,setTip]=useState("");const score=target===0?[96,74,72]:target===1?[86,94,82]:[78,92,94];return <main>
<header><div className="brand"><span>▣</span>装机星图 <i>Beta</i></div><div className="nav"><button onClick={()=>setTip("预算区间已设为 ¥8,000–10,000")}>预算 ¥8,000–10,000⌄</button><button onClick={()=>setTip("外观偏好：纯白海景房")}>纯白海景房⌄</button></div><button onClick={()=>setTip("配置链接已复制")}>↗ 分享配置</button></header>
<div className="grid"><aside className="left"><p className="eyebrow">01 / 先说说你想做什么</p><h2>性能目标</h2><div className="targets">{targets.map((x,i)=><button className={target===i?"on":""} onClick={()=>setTarget(i)} key={x}><b>◉</b><span><strong>{x}</strong><small>{i===0?"赛博朋克 2077 · 光追高":i===1?"Premiere · 4K 多轨":"Stable Diffusion · 本地生成"}</small></span></button>)}</div><div className="preference"><span><p className="eyebrow">02 / 极客偏好</p><h2>静音与散热</h2></span><button className={quiet?"switch on":"switch"} onClick={()=>setQuiet(!quiet)}><i/></button></div><div className="list-head"><span><p className="eyebrow">03 / 推荐配置</p><h2>硬件清单</h2></span><b>{tuned?"¥8,899":"¥9,199"}</b></div><div className="parts">{parts.map((x,i)=><button onClick={()=>setTip(`${x[0]} ${x[1]} 已在机箱中高亮`)} key={x[0]}><em className={`ico i${i}`}>{i===0?"▣":i===1?"▰":i===4?"✺":"ϟ"}</em><span><small>{x[0]}</small><strong>{x[1]}</strong><small>{x[2]}</small></span><b>›</b></button>)}</div></aside>
<section className="canvas"><div className="canvas-title"><span><p className="eyebrow">实时装配预览</p><h1>{target===0?"2K 光追 + 剪辑兼顾":targets[target]}</h1></span><b className="good">● 兼容性通过</b></div><div className="stage"><div className="case"><div className="top"/><div className="body"><div className="fans"><i/><i/><i/></div><div className="cpu"><i/><i/><i/><i/></div><div className="ram"><i/><i/></div><div className="gpu">GEFORCE RTX <i/></div><div className="psu">750W</div><div className="wires">〰〰</div></div><div className="front"/></div><span className="measure m1">330 mm</span><span className="measure m2">155 mm</span><b className="fit">✓ 空间余量充足</b></div><div className="cards"><article><em>ϟ</em><span><small>实时功耗</small><strong>468 <i>W</i></strong></span><b>峰值 632W</b><i className="line power"/></article><article><em>✺</em><span><small>风道效率</small><strong>{quiet?"静音":"优良"}</strong></span><b>{quiet?"32 dBA":"5 进 4 出"}</b><i className="line air"/></article></div><div className="radar"><div><span><p className="eyebrow">性能瓶颈雷达</p><h2>配置均衡度 <b>92</b><small>/100</small></h2></span><em>黄金搭配</em></div>{targets.map((x,i)=><p key={x}><span>{x}</span><i><b style={{width:`${score[i]}%`}}/></i><strong>{score[i]}%</strong></p>)}</div></section>
<aside className="right"><section><p className="eyebrow">UPGRADE ROADMAP</p><h2>未来 3.5 年，<br/>仍能轻松应对。</h2><div className="timeline"><span>2026<b>现在</b></span><span>2027<b>可升 CPU</b></span><span>2028+<b>建议换显卡</b></span></div><div className="platform"><strong>AM5 平台 <b>升级潜力 A</b></strong><p>接口预计支持至 2027+，未来可直接单升 CPU。</p></div></section><section className="warn"><b>!</b><span><small>防背刺提醒</small><strong>显卡处于世代交替期</strong><p>如不急用，可关注下月新品价格。</p></span></section><section className="helper"><b>✦</b><span><small>新手装机提示</small><strong>先安装 CPU 与 M.2 固态硬盘，再将主板装入机箱。</strong></span></section><button className="adjust" onClick={()=>{setTuned(!tuned);setTip(tuned?"已还原性能优先配置":"已替换为性价比 SSD 与电源，性能变化 < 5%")}}>{tuned?"还原原始方案":"一键微调，压回预算"}<b>→</b></button></aside></div>{tip&&<output>{tip}<button onClick={()=>setTip("")}>×</button></output>}</main>}
